name: "Plan changes"
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - edited
            - ready_for_review

jobs:
    Plan:
        name: Plan infrastructure
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        env:
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              run: terraform init

            - name: Terraform fmt
              run: |
                terraform fmt --check

            - name: Terraform validate
              run: terraform validate

            - name: Terraform plan
              run: |
                terraform plan \
                --var-file variables/modelkit.tfvars \
                --out tfplan
